name: Deploy
on:
  workflow_dispatch:
    branches:
      - test
  push:
    branches:
      - master
    paths:
      - 'infrastructure/**'
      - '.github/workflows/main.yml'


jobs:
  checkov:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure
          framework: terraform 

  terraform_plan:
    defaults:
      run:
        working-directory: infrastructure
    runs-on: ubuntu-latest
    needs: checkov
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan       

  terraform_apply:
    defaults:
      run:
        working-directory: infrastructure
    runs-on: ubuntu-latest
    environment:
      name: approval
    needs: terraform_plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan
    - name: Terraform_Apply
      run: make run_apply  
